"""
Episodic Memory Implementation

Provides persistent storage for session history using SQLite.
Stores the complete conversation history that persists across restarts.
"""

from typing import List, Dict, Any, Optional
import logging

from .abc import MemoryBackend, MemoryItem

logger = logging.getLogger(__name__)


class EpisodicMemory(MemoryBackend):
    """
    Episodic Memory: Session history persistence.
    
    Uses SQLite database to store complete conversation history.
    This memory persists across application restarts and contains
    the full context of past sessions.
    """
    
    def __init__(self):
        """
        Initialize Episodic Memory.
        
        Uses the existing persistence layer from app.core.persistence.
        """
        self._ChatMessage = None
        self._db_session = None
        logger.info("EpisodicMemory initialized")
    
    def _get_persistence_classes(self):
        """Lazy import to avoid circular dependencies."""
        if self._ChatMessage is None:
            from app.core.persistence import ChatMessage, db_session
            self._ChatMessage = ChatMessage
            self._db_session = db_session
        return self._ChatMessage, self._db_session
    
    async def add(self, item: MemoryItem) -> str:
        """
        Add a memory item to episodic memory (persist to SQLite).
        
        Args:
            item: The MemoryItem to store
            
        Returns:
            The ID of the stored item (generated by DB)
        """
        ChatMessage, db_session = self._get_persistence_classes()
        
        # Extract role from metadata or default to "user"
        role = item.metadata.get("role", "user")
        content = item.content
        
        try:
            with db_session() as db:
                # Ensure session exists
                from app.core.persistence import _ensure_session
                _ensure_session(db, item.session_id)
                
                msg = ChatMessage(
                    session_id=item.session_id,
                    role=role,
                    content=content
                )
                db.add(msg)
                db.flush()  # Get the ID
                
                # Return the database ID
                item_id = str(msg.id)
                logger.debug(f"Added message to episodic memory: session={item.session_id}, role={role}")
                return item_id
                
        except Exception as e:
            logger.error(f"Failed to add to episodic memory: {e}")
            return ""
    
    async def search(
        self, 
        query: str, 
        memory_type: Optional[str] = None,
        user_id: Optional[str] = None, 
        limit: int = 5
    ) -> List[MemoryItem]:
        """
        Search episodic memory for relevant sessions.
        
        Note: For episodic memory, we search by session_id (user_id parameter).
        Full-text search could be implemented with SQLite FTS in the future.
        
        Args:
            query: Search query (currently not used - returns recent history)
            memory_type: Ignored for episodic memory
            user_id: Session ID to search in
            limit: Maximum number of items to return
            
        Returns:
            List of recent MemoryItems
        """
        if not user_id:
            return []
        
        # For now, return recent messages from the session
        history = await self.get_session_history(user_id, limit)
        return history
    
    async def get_session_history(
        self, 
        session_id: str, 
        limit: int = 100
    ) -> List[MemoryItem]:
        """
        Get all messages for a specific session.
        
        Args:
            session_id: The session ID to retrieve history for
            limit: Maximum number of items to return
            
        Returns:
            List of MemoryItems in chronological order
        """
        ChatMessage, db_session = self._get_persistence_classes()
        
        try:
            with db_session() as db:
                rows = (
                    db.query(ChatMessage)
                    .filter(ChatMessage.session_id == session_id)
                    .order_by(ChatMessage.created_at.asc(), ChatMessage.id.asc())
                    .limit(limit)
                    .all()
                )
            
            items = []
            for i, row in enumerate(rows):
                # Normalize role for consistency
                role = row.role
                if role == "assistant" or role == "model":
                    role = "model"
                
                # Try to extract text content from JSON if needed
                content = row.content
                
                item = MemoryItem(
                    id=str(row.id),
                    content=content,
                    memory_type="episodic",
                    session_id=session_id,
                    user_id=session_id,  # For episodic, user_id = session_id
                    timestamp=row.created_at.isoformat() if row.created_at else "",
                    metadata={"role": role, "created_at": str(row.created_at) if row.created_at else ""}
                )
                items.append(item)
            
            logger.debug(f"Retrieved {len(items)} messages from episodic memory for session: {session_id}")
            return items
            
        except Exception as e:
            logger.error(f"Failed to get session history: {e}")
            return []
    
    async def delete(self, memory_id: str) -> bool:
        """
        Delete a specific message from episodic memory.
        
        Args:
            memory_id: The ID of the message to delete
            
        Returns:
            True if deleted, False otherwise
        """
        ChatMessage, db_session = self._get_persistence_classes()
        
        try:
            with db_session() as db:
                row = db.query(ChatMessage).filter(ChatMessage.id == int(memory_id)).first()
                if row:
                    db.delete(row)
                    logger.debug(f"Deleted message from episodic memory: {memory_id}")
                    return True
                return False
                
        except Exception as e:
            logger.error(f"Failed to delete from episodic memory: {e}")
            return False
    
    async def get_all(self, user_id: str, limit: int = 100) -> List[MemoryItem]:
        """
        Get all episodic memories for a user across sessions.
        
        Note: For episodic memory, we currently only support session-based retrieval.
        This could be extended to support user-based aggregation.
        
        Args:
            user_id: User ID (currently maps to session_id)
            limit: Maximum number of items to return
            
        Returns:
            List of MemoryItems
        """
        # Delegate to session history for now
        return await self.get_session_history(user_id, limit)
    
    def format_session_history(self, session_id: str, limit: int = 20) -> str:
        """
        Format session history as a string for LLM context.
        
        Synchronous version that returns formatted conversation history.
        
        Args:
            session_id: The session ID to format
            limit: Maximum number of messages
            
        Returns:
            Formatted string with role: content pairs
        """
        import asyncio
        
        # Run async function in sync context
        try:
            loop = asyncio.get_event_loop()
            if loop.is_running():
                # Can't use run_until_complete in async context
                # Just return empty for now
                return ""
            else:
                items = loop.run_until_complete(self.get_session_history(session_id, limit))
        except RuntimeError:
            # No event loop, create new one
            items = asyncio.run(self.get_session_history(session_id, limit))
        
        if not items:
            return ""
        
        formatted_parts = []
        for item in items:
            role = item.metadata.get("role", "user")
            formatted_parts.append(f"{role}: {item.content}")
        
        return "\n".join(formatted_parts)


# Singleton instance
_episodic_memory_instance: Optional[EpisodicMemory] = None


def get_episodic_memory() -> EpisodicMemory:
    """
    Get the singleton EpisodicMemory instance.
    
    Returns:
        The global EpisodicMemory instance
    """
    global _episodic_memory_instance
    if _episodic_memory_instance is None:
        _episodic_memory_instance = EpisodicMemory()
    return _episodic_memory_instance
