import logging
from pathlib import Path
from typing import Optional

from pydantic import BaseModel, Field

logger = logging.getLogger("navibot.skills.file_tools")

WORKSPACE_SESSIONS = Path(__file__).resolve().parents[3] / "workspace" / "sessions"


class ListArtifactsArgs(BaseModel):
    session_id: str = Field(default="default", description="Session ID to list artifacts for")


class ListArtifactsResult(BaseModel):
    session_id: str
    artifacts: list[dict] = Field(default_factory=list)
    error: Optional[str] = None


class ReadArtifactArgs(BaseModel):
    session_id: str = Field(..., description="Session ID")
    filename: str = Field(..., description="Filename within the session artifacts directory")


class ReadArtifactResult(BaseModel):
    session_id: str
    filename: str
    content: str = ""
    error: Optional[str] = None


def list_artifacts(session_id: str = "default") -> str:
    """
    List all artifact files generated by the agent in a session's /workspace/sessions/{session_id}/artifacts directory.
    Returns filename, size, and last-modified timestamp.
    """
    result = ListArtifactsResult(session_id=session_id, artifacts=[], error=None)
    session_dir = WORKSPACE_SESSIONS / _safe_session_id(session_id) / "artifacts"

    if not session_dir.exists():
        return _serialize_list_result(result)

    try:
        for path in sorted(session_dir.iterdir()):
            if path.is_file():
                stat = path.stat()
                result.artifacts.append({
                    "filename": path.name,
                    "size_bytes": stat.st_size,
                    "modified_ts": int(stat.st_mtime * 1000),
                })
    except Exception as exc:
        logger.exception("list_artifacts failed for session %s", session_id)
        result.error = str(exc)

    return _serialize_list_result(result)


def read_artifact(session_id: str, filename: str) -> str:
    """
    Read the content of an artifact file from /workspace/sessions/{session_id}/artifacts/{filename}.
    """
    result = ReadArtifactResult(session_id=session_id, filename=filename, content="", error=None)
    safe_id = _safe_session_id(session_id)
    safe_name = _safe_filename(filename)
    artifact_path = WORKSPACE_SESSIONS / safe_id / "artifacts" / safe_name

    if not artifact_path.exists():
        result.error = f"File not found: {filename}"
        return _serialize_read_result(result)

    if not artifact_path.is_file():
        result.error = f"Not a file: {filename}"
        return _serialize_read_result(result)

    try:
        content_bytes = artifact_path.read_bytes()
        result.content = content_bytes.decode("utf-8", errors="replace")[:500_000]
    except Exception as exc:
        logger.exception("read_artifact failed for %s/%s", session_id, filename)
        result.error = str(exc)

    return _serialize_read_result(result)


def _safe_session_id(session_id: str) -> str:
    import re
    safe = re.sub(r"[^a-zA-Z0-9_-]", "_", session_id.strip())[:64]
    return safe or "default"


def _safe_filename(filename: str) -> str:
    import re
    name = filename.strip().lstrip("/")
    safe = re.sub(r"[^a-zA-Z0-9_.-]", "_", name)
    return safe


def _serialize_list_result(result: ListArtifactsResult) -> str:
    return result.model_dump_json(include={"session_id", "artifacts", "error"})


def _serialize_read_result(result: ReadArtifactResult) -> str:
    return result.model_dump_json(include={"session_id", "filename", "content", "error"})
